RedisExchangeAPI.Web/Models/ErrorViewModel.cs
namespace RedisExchangeAPI.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RedisExchangeAPI.Web/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using StackExchange.Redis;

namespace RedisExchangeAPI.Web.Controllers
{
    public class BaseController : Controller
    {
        protected readonly IDatabase _redisDb;

        public BaseController(IDatabase redisDb)
        {
            _redisDb = redisDb;
        }
    }
}

RedisExchangeAPI.Web/Controllers/HashTypeController.cs
using Microsoft.AspNetCore.Mvc;
using StackExchange.Redis;

namespace RedisExchangeAPI.Web.Controllers
{
    public class HashTypeController : BaseController
    {
        private readonly string key = "hashTypeNames";

        public HashTypeController(IDatabase redisDb) : base(redisDb)
        {
        }

        public IActionResult Index()
        {
            Dictionary<string, string> keyValuePairs = new();

            if (_redisDb.KeyExists(key))
            {
                _redisDb.HashGetAll(key).ToList().ForEach(x => keyValuePairs.Add(x.Name, x.Value));
            }

            return View(keyValuePairs);
        }

        [HttpPost]
        public IActionResult Add(string name, string value)
        {
            _redisDb.HashSet(key, name, value);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(string name)
        {
            _redisDb.HashDelete(key, name);
            return RedirectToAction(nameof(Index));
        }
    }
}

RedisExchangeAPI.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPI.Web.Models;
using System.Diagnostics;

namespace RedisExchangeAPI.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RedisExchangeAPI.Web/Controllers/ListTypeController.cs
using Microsoft.AspNetCore.Mvc;
using StackExchange.Redis;

namespace RedisExchangeAPI.Web.Controllers
{
    public class ListTypeController : BaseController
    {
        private readonly string key = "names";
        public ListTypeController(IDatabase redisDb) : base(redisDb)
        {
        }

        public IActionResult Index()
        {
            List<string> nameList = new();

            if (_redisDb.KeyExists(key))
            {
                nameList = _redisDb.ListRange(key).Select(rv => rv.ToString()).ToList();
            }

            return View(nameList);
        }

        [HttpPost]
        public IActionResult Add(string name)
        {
            _redisDb.ListRightPush(key, name);
            //_redisDb.ListLeftPush(key, name);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(string name)
        {
            _redisDb.ListRemove(key, name);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveFirst()
        {
            _redisDb.ListLeftPop(key);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveLast()
        {
            _redisDb.ListRightPop(key);
            return RedirectToAction(nameof(Index));
        }
    }
}

RedisExchangeAPI.Web/Controllers/SetTypeController.cs
using Microsoft.AspNetCore.Mvc;
using StackExchange.Redis;

namespace RedisExchangeAPI.Web.Controllers
{
    public class SetTypeController : BaseController
    {
        private readonly string key = "setTypeNames";
        public SetTypeController(IDatabase redisDb) : base(redisDb)
        {
        }
        public IActionResult Index()
        {
            HashSet<string> nameList = new();

            if (_redisDb.KeyExists(key))
            {
                nameList = _redisDb.SetMembers(key).Select(rv => rv.ToString()).ToHashSet();
            }

            return View(nameList);
        }

        [HttpPost]
        public IActionResult Add(string name)
        {
            if (!_redisDb.KeyExists(key)) _redisDb.KeyExpire(key, DateTime.Now.AddMinutes(5));

            _redisDb.SetAdd(key, name);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(string name)
        {
            _redisDb.SetRemove(key, name);
            return RedirectToAction(nameof(Index));
        }
    }
}

RedisExchangeAPI.Web/Controllers/SortedSetTypeController.cs
using Microsoft.AspNetCore.Mvc;
using StackExchange.Redis;

namespace RedisExchangeAPI.Web.Controllers
{
    public class SortedSetTypeController : BaseController
    {
        private readonly string key = "sortedSetTypeNames";

        public SortedSetTypeController(IDatabase redisDb) : base(redisDb)
        {
        }

        public IActionResult Index()
        {
            HashSet<string> nameList = new();

            if (_redisDb.KeyExists(key))
            {
                //nameList = _redisDb.SortedSetScan(key).Select(x => x.ToString()).ToHashSet();
                nameList = _redisDb.SortedSetRangeByRank(key, order: Order.Descending).Select(x => x.ToString()).ToHashSet();
            }

            return View(nameList);
        }

        [HttpPost]
        public IActionResult Add(string name, double score)
        {
            _redisDb.SortedSetAdd(key, name, score);
            _redisDb.KeyExpire(key, DateTime.Now.AddMinutes(5));

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(string name)
        {
            _redisDb.SortedSetRemove(key, name);
            return RedirectToAction(nameof(Index));
        }
    }
}

RedisExchangeAPI.Web/Controllers/StringTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Distributed;
using RedisExchangeAPI.Web.Services;
using StackExchange.Redis;

namespace RedisExchangeAPI.Web.Controllers
{
    public class StringTypeController : BaseController
    {
        private readonly string key = "stringTypeNames";
        private readonly string count= "stringTypeVisitorCount";

        public StringTypeController(IDatabase redisDb) : base(redisDb)
        {
        }

        public IActionResult Index()
        {
            _redisDb.StringSet(key, "ahmet sarikaya");
            _redisDb.StringSet(count, 100);
            return View();
        }

        public IActionResult Show()
        {
            //_redisDb.StringIncrement(count, 1);
            _redisDb.StringDecrement(count, 1);

            //var cachedName = _redisDb.StringGet(key);
            //var cachedName = _redisDb.StringGetRange(key, 0, 3);
            var cachedName = _redisDb.StringLength(key);

            ViewBag.cachedName = cachedName.ToString();

            return View();
        }

        public IActionResult ImageCache()
        {
            string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/togg.jpg");
            byte[] imageByte = System.IO.File.ReadAllBytes(path);
            _redisDb.StringSet("img:1", imageByte);
            return View();
        }

        public IActionResult ImageUrl()
        {
            byte[] imageByte = _redisDb.StringGet("img:1");
            return File(imageByte, "image/jpg");
        }
    }
}

RedisExchangeAPI.Web/Views/HashType/Index.cshtml
@model Dictionary<string, string>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<form asp-controller="HashType" asp-action="Add" method="post" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" value="" />
    <input type="text" name="value" value="" />
    <input type="submit" name="submit" value="submit" />
</form>
<hr />
@if (Model.Count > 0)
{
    <ul>
        @foreach (var keyValuePair in Model)
        {
            <li>
                <span>@keyValuePair.Key : @keyValuePair.Value</span>
                <a asp-controller="HashType" asp-action="Remove" asp-route-name="@keyValuePair.Key">Remove</a>
            </li>
        }
    </ul>
}
else
{
    <p>No value added yet!</p>
}

RedisExchangeAPI.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RedisExchangeAPI.Web/Views/ListType/Index.cshtml
@model List<string>
@{
    ViewData["Title"] = "Index";
    List<string> nameList = ViewBag.NameList;
}

<h1>Index</h1>

<form asp-controller="ListType" asp-action="Add" method="post" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" value="" />
    <input type="submit" name="submit" value="submit" />
</form>
<hr />

<div class="d-flex justify-content-between">
    <a asp-controller="ListType" asp-action="RemoveFirst">Remove First</a>
    <a asp-controller="ListType" asp-action="RemoveLast">Remove Last</a>
</div>
<div>
    @if (Model.Count > 0)
    {
        <ul>
            @foreach (string name in Model)
            {
                <li class="d-flex justify-content-between">
                    <span>@name</span>
                    <a asp-controller="ListType" asp-action="Remove" asp-route-name="@name">Remove</a>
                </li>
            }
        </ul>
    }
    else
    {
        <p>List is empty!</p>
    }
</div>

RedisExchangeAPI.Web/Views/SetType/Index.cshtml
@model HashSet<string>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<form asp-controller="SetType" asp-action="Add" method="post" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" value="" />
    <input type="submit" name="submit" value="submit" />
</form>
<hr />
@if (Model.Count > 0)
{
    <ul>
        @foreach (var name in Model)
        {
            <li>
                <span>@name</span>
                <a asp-controller="SetType" asp-action="Remove" asp-route-name="@name">Remove</a>
            </li>
        }
    </ul>
}
else
{
    <p>No value added yet!</p>
}

RedisExchangeAPI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RedisExchangeAPI.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RedisExchangeAPI.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RedisExchangeAPI.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RedisExchangeAPI.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RedisExchangeAPI.Web/Views/StringType/ImageCache.cshtml
@{
    ViewData["Title"] = "ImageCache";
}

<h1>ImageCache</h1>

RedisExchangeAPI.Web/Views/StringType/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

RedisExchangeAPI.Web/Views/StringType/Show.cshtml
@{
    ViewData["Title"] = "Show";
}

<h1>Show</h1>

<p>Cached Name : @ViewBag.cachedName</p>